### ISSUE TITLE
[1.12.2] No feathers

### ISSUE THREAD

**Issue by Leonetienne** [axelrindle/minecraft-chicken-drop-feathers#1]
I wanted to test this mod before including it in my survival world.
I've went on a superflat world in creative, spawned about a gorillian chickens, and waited 10 mins.

Eggs everywhere, but not a single feather.

Mod version: 1.0
Forgelin: 1.8.3
Forge: 14.23.5.2847

Says chickenDropFeathers and Forgelin are loaded.

**Comment by axelrindle** [comment]
Hm, that's weird 🤔 I will test the given versions ASAP.

**Comment by axelrindle** [comment]
Working on a complete re-implementation of the mod. The new implementation should fix your issue as soon as it's released.
