### ISSUE TITLE
1.19.x Fabric version please

### ISSUE THREAD

**Issue by TheMerryRogue** [axelrindle/minecraft-chicken-drop-feathers#11]
Please create a 1.19.x Fabric version when possible. Thank you!

**Comment by axelrindle** [comment]
Hi there, I just [created a pre-release](https://github.com/axelrindle/minecraft-chicken-drop-feathers/releases/tag/1.19-rc.1) for Minecraft 1.19 which supports Forge, Fabric and Quilt. Please download the according version and report any bugs you find.
