### ISSUE TITLE
Split Modrinth release into two versions

### ISSUE THREAD

**Issue by copygirl** [axelrindle/minecraft-chicken-drop-feathers#12]
We're using packwiz to manage our modpack and I realized when installing Chicken Drop Feathers, it picked the Fabric version instead of Forge. This appears to be the case because you have [a version](https://modrinth.com/mod/chicken-drop-feathers/version/FjxOiAaG) that's marked as compatible with both Fabric and Forge, but then multiple files attached to that version. I believe this usage is incorrect, and there's no good way for an automated process such as a launcher or updater to find out which file it is supposed to use. At this time I had to manually point the download at the right URL and update the hash myself.

Would you please create two separate versions on Modrinth, one for Forge and one for Fabric? This should resolve the issue for us, and others using your mod. And I believe it is the correct way to use Modrinth. (Though feel free to ask the Modrinth people for confirmation.) Thank you!

**Comment by axelrindle** [comment]
I'll look into this on the weekend.

**Comment by axelrindle** [comment]
Done ✨

Sorry for the delay.

**Comment by copygirl** [comment]
Sweet! I already updated this for our pack. Thank you.
