### ISSUE TITLE
Fabric version

### ISSUE THREAD

**Issue by d4rkm0nkey** [axelrindle/minecraft-chicken-drop-feathers#3]
I would love to see this mod for the Fabric Loader in version 1.16.5

**Comment by axelrindle** [comment]
Hi @d4rkm0nkey , thank you for the request. As I've never worked with Fabric before, it might take some time to accomplish that. But I will see what I can do.

**Comment by StephenESC** [comment]
I’d love to see this as well! Thanks for considering it. 😊
