### ISSUE TITLE
Include a config file for changing the droprate

### ISSUE THREAD

**Issue by dkaarvand** [axelrindle/minecraft-chicken-drop-feathers#7]
Not much to write other than it would have been really nice to have it. They seem to drop far more feathers than egg, seems somewhat unbalanced.

**Comment by axelrindle** [comment]
Hello!

Thanks for the suggestion. I will try to implement this ASAP, but I have not much free time at the moment. If you're experienced with Forge and/or Fabric, feel free to send a PR!
