### ISSUE TITLE
1.18.1 for Forge, please.

### ISSUE THREAD

**Issue by mgwerner** [axelrindle/minecraft-chicken-drop-feathers#9]
**Describe the problem**
Some X does not work

**Additional context**
Is there anything else to know?

**Environment**
Modloader: Fabric / Forge
Modloader Version:
Minecraft Version: 1.16.5

**Logs**
Please attach any log output that might be helpful (such as your `.minecraft/logs/latest.log` or if that contains sensitive information just the output the launcher shows when the game crashes)

**Comment by axelrindle** [comment]
This is not a bug report.
